# Generated by Django 3.2.3 on 2021-05-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paint',
            name='type',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
