# Generated by Django 3.2.3 on 2021-05-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_paint_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paint',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
