# Generated by Django 3.2.3 on 2021-05-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_paint_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paint',
            name='stock',
            field=models.IntegerField(auto_created=True, default=0),
        ),
    ]
