# Generated by Django 3.2.3 on 2021-05-31 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210528_1338'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='paint',
            table='main_paint',
        ),
    ]
