# Generated by Django 3.2.3 on 2021-05-31 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_paint_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='paint',
            table='main_paint',
        ),
    ]
