# Generated by Django 2.2.10 on 2021-06-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_paint_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='paint',
            name='location',
            field=models.CharField(default='İstanbul', max_length=200),
        ),
        migrations.AlterField(
            model_name='paint',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
