# Generated by Django 3.2.3 on 2021-06-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_paint_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paint',
            name='location',
            field=models.CharField(choices=[('IST', 'İstanbul'), ('YLV', 'Yalova')], default='IST', max_length=3),
        ),
    ]
