# Generated by Django 3.2.3 on 2021-06-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_paint_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='paint',
            name='weight',
            field=models.CharField(default='20 KG', max_length=200),
        ),
        migrations.AlterField(
            model_name='paint',
            name='location',
            field=models.CharField(choices=[('İstanbul', 'İstanbul'), ('Yalova', 'Yalova')], default='İstanbul', max_length=200),
        ),
    ]
