# Generated by Django 3.2.3 on 2021-06-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210606_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paint',
            name='weight',
            field=models.CharField(default='20KG', max_length=200),
        ),
    ]
