# Generated by Django 3.2.3 on 2021-06-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_paint_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paint',
            name='weight',
            field=models.CharField(max_length=200),
        ),
    ]
