# Generated by Django 3.2.3 on 2021-06-06 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_paint_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='paint',
            name='choice',
            field=models.CharField(choices=[('Boya', 'Boya'), ('Tiner', 'Tiner')], default='Boya', max_length=200),
        ),
    ]
